#include "instruction_parse.h"

int parse_instruction(instruction* instruction){return 1;}
int parse_instruction_a(instruction* instruction){return 1;}
int parse_instruction_a_n(instruction* instruction){return 1;}
int parse_instruction_a_n_a(instruction* instruction){return 1;}
int parse_instruction_a_n_a_a_n_a(instruction* instruction){return 1;}
int parse_instruction_a_n_a_n(instruction* instruction){return 1;}
int parse_instruction_a_n_n(instruction* instruction){return 1;}
int parse_instruction_a_n_n_a(instruction* instruction){return 1;}
int parse_instruction_a_n_n_n(instruction* instruction){return 1;}
void parse_bit_string(char *s_p){}
int parse_instruction_a_n_n_b(instruction* instruction){return 1;}
int parse_instruction_a_n_n_n_b(instruction* instruction){return 1;}
int parse_instruction_a_n_n_n_n(instruction* instruction){return 1;}
int parse_instruction_a_n_n_n_n_n(instruction* instruction){return 1;}
int parse_instruction_b(instruction* instruction){return 1;}
int parse_instruction_b_n(instruction* instruction){return 1;}
int parse_instruction_c(instruction* instruction){return 1;}
int parse_instruction_c_c_n_a_a(instruction* instruction){return 1;}
int parse_instruction_c_n(instruction* instruction){return 1;}
int parse_instruction_c_n_a(instruction* instruction){return 1;}
int parse_instruction_i(instruction* instruction){return 1;}
int parse_instruction_i_i_n_a_a(instruction* instruction){return 1;}
int parse_instruction_i_n(instruction* instruction){return 1;}
int parse_instruction_i_n_a(instruction* instruction){return 1;}
int parse_instruction_l(instruction* instruction){return 1;}
int parse_instruction_n(instruction* instruction){return 1;}
int parse_instruction_n_a(instruction* instruction){return 1;}
int parse_instruction_n_a_n_a_a_n_a(instruction* instruction){return 1;}
int parse_instruction_n_b(instruction* instruction){return 1;}
int parse_instruction_n_n(instruction* instruction){return 1;}
int parse_instruction_n_n_n(instruction* instruction){return 1;}
int parse_instruction_n_n_n_n(instruction* instruction){return 1;}
int parse_instruction_n_n_n_n_n(instruction* instruction){return 1;}
int parse_instruction_n_n_n_n_n_n_n(instruction* instruction){return 1;}
int parse_instruction_on(instruction* instruction){return 1;}
int parse_instruction_s(instruction* instruction){return 1;}
int parse_instruction_s2(instruction* instruction){return 1;}
int parse_instruction_s2_n_a(instruction* instruction){return 1;}
int parse_directive(instruction* instruction){return 1;}
int parse_directive_a(instruction* instruction){return 1;}
int parse_directive_depend(instruction* instruction){return 1;}
int parse_directive_desc(instruction* instruction){return 1;}
int parse_directive_desc0(instruction* instruction){return 1;}
int parse_directive_descn(instruction* instruction){return 1;}
int parse_directive_implab(instruction* instruction){return 1;}
int parse_directive_labels(instruction* instruction){return 1;}
int parse_directive_module(instruction* instruction){return 1;}
int parse_directive_n(instruction* instruction){return 1;}
int parse_directive_nu(instruction* instruction){return 1;}
int parse_directive_n_l(instruction* instruction){return 1;}
int parse_directive_n_n_t(instruction* instruction){return 1;}
int parse_directive_label(instruction* instruction){return 1;}
int parse_directive_record(instruction* instruction){return 1;}
int parse_directive_string(instruction* instruction){return 1;}
