stages:
  - build
  - test-interpreter
  - test-interworking

.base:
  image: camilstaps/abc-interpreter
  before_script:
    - ln -s "$PWD/src/optimise" /opt/clean/lib/exe/optimise
    - ln -s "$PWD/src/bcgen" /opt/clean/lib/exe/bcgen
    - ln -s "$PWD/src/link" /opt/clean/lib/exe/bclink
    - make -C src
    - clm -bytecode -O _system

build:
  extends: .base
  stage: build
  script:
    - CFLAGS='-DDEBUG_ALL_INSTRUCTIONS -DDEBUG_CLEAN_LINKS=10 -DDEBUG_GARBAGE_COLLECTOR=10' make -B -C src

test-gc:
  extends: .base
  stage: test-interpreter
  script:
    - cd test
    - CFLAGS=-DDEBUG_GARBAGE_COLLECTOR_MARKING ./run_tests.sh -o weird_types
    - CFLAGS=-DDEBUG_GARBAGE_COLLECTOR_MARKING ./run_tests.sh --32-bit -o weird_types

benchmark-x64:
  extends: .base
  stage: test-interpreter
  script:
    - cd test
    - ./run_tests.sh --benchmark --fast

benchmark-x86:
  extends: .base
  stage: test-interpreter
  script:
    - cd test
    - ./run_tests.sh --32-bit --benchmark --fast

interworking-from-Start:
  extends: .base
  stage: test-interworking
  script:
    - (cd test; ./run_tests.sh -Rqo functions)
    - cd src
    - make -B CodeSharing
    - ./CodeSharing 2>/dev/null | grep '^\[\(37,\)*37\]$'
    - CFLAGS='-DCOMPUTED_GOTOS -Ofast -fno-unsafe-math-optimizations' make -B CodeSharing
    - ./CodeSharing 2>/dev/null | grep '^\[\(37,\)*37\]$'

interworking-with-GraphCopy:
  extends: .base
  stage: test-interworking
  script:
    - cd src
    - make -B GraphTest
    - ./GraphTest 2>/dev/null | grep '^\[\(37,\)*37\]$'
    - CFLAGS='-DCOMPUTED_GOTOS -Ofast -fno-unsafe-math-optimizations' make -B GraphTest
    - ./GraphTest 2>/dev/null | grep '^\[\(37,\)*37\]$'
