.base:
  image: camilstaps/clean:nightly
  before_script:
    - dpkg --add-architecture i386
    - apt-get update -qq
    - apt-get install -y -qq --no-install-recommends build-essential gcc-multilib time bc libncurses5-dev libncurses5-dev:i386 git
    - install_clean_nightly.sh base lib-platform lib-dynamics lib-graphcopy

    - git clone https://gitlab.science.ru.nl/cstaps/clean-tools /tmp/clean-tools
    - make -C /tmp/clean-tools/clm -f Makefile.linux64
    - mv /tmp/clean-tools/clm/clm /opt/clean/bin

    - ln -s "$PWD/src/optimise" /opt/clean/lib/exe/optimise
    - ln -s "$PWD/src/bcgen" /opt/clean/lib/exe/bcgen
    - ln -s "$PWD/src/link" /opt/clean/lib/exe/bclink
    - make -C src
    - clm -bytecode -O _system

build:
  extends: .base
  script:
    - CFLAGS=-DDEBUG_ALL_INSTRUCTIONS make -B -C src
    - CFLAGS=-DDEBUG_GARBAGE_COLLECTOR=10 make -B -C src

test-gc:
  extends: .base
  script:
    - cd test
    - CFLAGS=-DDEBUG_GARBAGE_COLLECTOR_MARKING ./run_tests.sh -o weird_types
    - CFLAGS=-DDEBUG_GARBAGE_COLLECTOR_MARKING ./run_tests.sh --32-bit -o weird_types

interworking-from-Start:
  extends: .base
  script:
    - (cd test; ./run_tests.sh -Rqo functions)
    - cd src
    - make -B CodeSharing
    - ./CodeSharing 2>/dev/null | grep '^\[\(37,\)*37\]$'
    - CFLAGS='-DCOMPUTED_GOTOS -Ofast -fno-unsafe-math-optimizations' make -B CodeSharing
    - ./CodeSharing 2>/dev/null | grep '^\[\(37,\)*37\]$'

interworking-with-GraphCopy:
  extends: .base
  script:
    - cd src
    - make -B GraphTest
    - ./GraphTest 2>/dev/null | grep '^\[\(37,\)*37\]$'
    - CFLAGS='-DCOMPUTED_GOTOS -Ofast -fno-unsafe-math-optimizations' make -B GraphTest
    - ./GraphTest 2>/dev/null | grep '^\[\(37,\)*37\]$'

benchmark:
  extends: .base
  script:
    - cd ../test
    - ./run_tests.sh --benchmark --fast

benchmark-x86:
  extends: .base
  script:
    - cd ../test
    - ./run_tests.sh --32-bit --benchmark --fast
