test:
  image: "camilstaps/clean:base"
  before_script:
    - apt-get update -qq
    - apt-get install -y -qq --no-install-recommends curl tar build-essential gcc-multilib time bc
    - curl ftp://ftp.cs.ru.nl/pub/Clean/builds/linux-x64/clean-base-linux-x64-latest.tgz | tar xzv --strip-components=1 -C /opt/clean
    - curl ftp://ftp.cs.ru.nl/pub/Clean/builds/linux-x64/clean-lib-platform-linux-x64-latest.tgz | tar xzv --strip-components=1 -C /opt/clean
  script:
    - cd test
    - ./run_tests.sh
    - ./run_tests.sh --32-bit
    - ./run_tests.sh --benchmark --fast
    - ./run_tests.sh --32-bit --benchmark --fast
