test:
  image: "camilstaps/clean:nightly"
  before_script:
    - dpkg --add-architecture i386
    - apt-get update -qq
    - apt-get install -y -qq --no-install-recommends build-essential gcc-multilib time bc libncurses5-dev libncurses5-dev:i386 git
    - install_clean_nightly.sh base lib-platform lib-dynamics lib-graphcopy

    - git clone https://gitlab.science.ru.nl/cstaps/clean-tools /tmp/clean-tools
    - make -C /tmp/clean-tools/clm -f Makefile.linux64
    - mv /tmp/clean-tools/clm/clm /opt/clean/bin

    - ln -s "$PWD/src/optimise" /opt/clean/exe/optimise
    - ln -s "$PWD/src/bcgen" /opt/clean/exe/bcgen
    - ln -s "$PWD/src/link" /opt/clean/exe/bclink
    - clm -bytecode -S _system
  script:
    - cd src
    - CFLAGS=-DDEBUG_ALL_INSTRUCTIONS make -B
    - CFLAGS=-DDEBUG_GARBAGE_COLLECTOR=10 make -B

    - (cd ../test; ./run_tests.sh -Rqo functions)
    - make -B CodeSharing
    - ./CodeSharing 2>/dev/null | grep '^\[\(37,\)*37\]$'
    - CFLAGS='-DCOMPUTED_GOTOS -Ofast -fno-unsafe-math-optimizations' make -B CodeSharing
    - ./CodeSharing 2>/dev/null | grep '^\[\(37,\)*37\]$'

    - cd ../test
    - ./run_tests.sh --benchmark --fast
    - ./run_tests.sh --32-bit --benchmark --fast

    - CFLAGS=-DDEBUG_GARBAGE_COLLECTOR_MARKING ./run_tests.sh -o weird_types
    - CFLAGS=-DDEBUG_GARBAGE_COLLECTOR_MARKING ./run_tests.sh --32-bit -o weird_types
