test:
  image: "camilstaps/clean:base"
  before_script:
    - dpkg --add-architecture i386
    - apt-get update -qq
    - apt-get install -y -qq --no-install-recommends ca-certificates curl tar build-essential gcc-multilib time bc libncurses5-dev libncurses5-dev:i386
    - curl https://ftp.cs.ru.nl/Clean/builds/linux-x64/clean-base-linux-x64-latest.tgz | tar xzv --strip-components=1 -C /opt/clean
    - curl https://ftp.cs.ru.nl/Clean/builds/linux-x64/clean-lib-platform-linux-x64-latest.tgz | tar xzv --strip-components=1 -C /opt/clean
    - curl https://ftp.cs.ru.nl/Clean/builds/linux-x64/clean-lib-dynamics-linux-x64-latest.tgz | tar xzv --strip-components=1 -C /opt/clean
  script:
    - cd src
    - CFLAGS=-DDEBUG_ALL_INSTRUCTIONS make -B
    - CFLAGS=-DDEBUG_GARBAGE_COLLECTOR=10 make -B
    - cd ../test
    - ./run_tests.sh
    - ./run_tests.sh --32-bit
    - CFLAGS=-DDEBUG_GARBAGE_COLLECTOR_MARKING ./run_tests.sh -o weird_types
    - CFLAGS=-DDEBUG_GARBAGE_COLLECTOR_MARKING ./run_tests.sh --32-bit -o weird_types
    - ./run_tests.sh --benchmark --fast
    - ./run_tests.sh --32-bit --benchmark --fast
