s/_BOOL/BOOL/g
s/_CHAR/CHAR/g
s/_REAL/REAL/g
s/_dINT/dINT/g
s/_ARRAY@/ARRAY@/g
s/___ARRAY__@/__ARRAY__@/g
s/___STRING__/__STRING__/g
s/___Nil/__Nil/g
s/___Tuple/__Tuple/g
s/___cycle__in__spine/__cycle__in__spine/g
s/_ap_\([[:digit:]]\)/ap_\1/g
s/_e____system__kFinalizer/e____system__kFinalizer/g
s/_finalizer_list/finalizer_list/g
s/___interpret__garbage__collect/__interpret__garbage__collect/g
s/___interpret__add__shared__node/__interpret__add__shared__node/g
s/___interpret__evaluate__host/__interpret__evaluate__host/g
s/___interpret__evaluate__host__with__args/__interpret__evaluate__host__with__args/g
s/___interpret__copy__node__asm_redirect_node/__interpret__copy__node__asm_redirect_node/g
s/_e__ABC_PInterpreter_PInternal__\([dn]\)interpret/e__ABC_PInterpreter_PInternal__\1interpret/g
s/_e__ABC_PInterpreter__dDV__/e__ABC_PInterpreter__dDV__/g
s/_copy_interpreter_to_host/copy_interpreter_to_host/g
s/_small_integers/small_integers/g
s/_static_characters/static_characters/g
